// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eHQ.Estoque.Api.Infra;

namespace eHQ.Estoque.Api.Infra.Migrations
{
    [DbContext(typeof(EstoqueContext))]
    [Migration("20200503224159_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eHQ.Estoque.Api.Models.EstoqueRevista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<Guid?>("RevistaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RevistaId");

                    b.ToTable("EstoqueRevistas");
                });

            modelBuilder.Entity("eHQ.Estoque.Api.Models.Revista", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Revistas");
                });

            modelBuilder.Entity("eHQ.Estoque.Api.Models.EstoqueRevista", b =>
                {
                    b.HasOne("eHQ.Estoque.Api.Models.Revista", "Revista")
                        .WithMany()
                        .HasForeignKey("RevistaId");
                });

            modelBuilder.Entity("eHQ.Estoque.Api.Models.Revista", b =>
                {
                    b.HasOne("eHQ.Estoque.Api.Models.EstoqueRevista", null)
                        .WithOne()
                        .HasForeignKey("eHQ.Estoque.Api.Models.Revista", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
