// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eHQ.Estoque.Api.Infra;

namespace eHQ.Estoque.Api.Migrations
{
    [DbContext(typeof(EstoqueContext))]
    [Migration("20200330003244_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eHQ.Estoque.Api.Models.EstoqueRevista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ID_REVISTA")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ID_REVISTA");

                    b.ToTable("EstoqueRevistas");
                });

            modelBuilder.Entity("eHQ.Estoque.Api.Models.Revista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Revistas");
                });

            modelBuilder.Entity("eHQ.Estoque.Api.Models.EstoqueRevista", b =>
                {
                    b.HasOne("eHQ.Estoque.Api.Models.Revista", "Revista")
                        .WithMany()
                        .HasForeignKey("ID_REVISTA");
                });
#pragma warning restore 612, 618
        }
    }
}
